name: Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Debug, Release]
        platform: [AnyCPU, x64]

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: msbuild RunUO.sln /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: RunUO-${{ matrix.configuration }}-${{ matrix.platform }}
        path: Distribution/${{ matrix.configuration }}/
        retention-days: 30