name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Debug, Release]
        platform: [AnyCPU, x64]

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Framework
      uses: microsoft/setup-msbuild@v1.3

    - name: Restore dependencies
      run: dotnet restore RunUO.sln

    - name: Build
      run: msbuild RunUO.sln /p:Configuration=${{ matrix.configuration }} /p:Platform="${{ matrix.platform }}"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: RunUO-${{ matrix.configuration }}-${{ matrix.platform }}
        path: Distribution/${{ matrix.configuration }}/
        retention-days: 30