name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2022

    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup .NET Framework
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Restore NuGet packages
      run: nuget restore RunUO.sln

    - name: Build solution
      run: msbuild RunUO.sln /p:Configuration=${{ matrix.configuration }} /p:Platform="Any CPU" /p:TargetFrameworkVersion=v4.8

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: RunUO-${{ matrix.configuration }}
        path: Distribution/${{ matrix.configuration }}/
        retention-days: 30